before_script: bundle exec rake bundle
script: bundle exec rake test
language: ruby
rvm:
  - 2.0.0-p0
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - ree
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
env:
  - SAMPLE_APP=rails_4_0_0
  - SAMPLE_APP=rails_3_2_13
matrix:
  exclude:
    - rvm: 1.8.7
      env: SAMPLE_APP=rails_4_0_0
    - rvm: ree
      env: SAMPLE_APP=rails_4_0_0
    - rvm: jruby-18mode
      env: SAMPLE_APP=rails_4_0_0
    - rvm: rbx-18mode
      env: SAMPLE_APP=rails_4_0_0
