before_script: bundle exec rake bundle
script: bundle exec rake test
language: ruby
rvm:
- 2.4.1
- 2.3.4
- 2.2.7
- 2.1.10
env:
- SAMPLE_APP=rails_4_0_0
- SAMPLE_APP=rails_4_0_13
- SAMPLE_APP=rails_4_1_0
- SAMPLE_APP=rails_4_1_16 SIDEKIQ_SUPPORTED=true
- SAMPLE_APP=rails_4_2_0 SIDEKIQ_SUPPORTED=true
- SAMPLE_APP=rails_4_2_8 SIDEKIQ_SUPPORTED=true
- SAMPLE_APP=rails_5_0_3 SIDEKIQ_SUPPORTED=true TEST_AR=true
- SAMPLE_APP=rails_5_1_1 SIDEKIQ_SUPPORTED=true TEST_AR=true
matrix:
  exclude:
  - rvm: 2.4.1
    env: SAMPLE_APP=rails_4_0_0
  - rvm: 2.4.1
    env: SAMPLE_APP=rails_4_0_13
  - rvm: 2.4.1
    env: SAMPLE_APP=rails_4_1_0
  - rvm: 2.4.1
    env: SAMPLE_APP=rails_4_1_16 SIDEKIQ_SUPPORTED=true
  - rvm: 2.4.1
    env: SAMPLE_APP=rails_4_2_0 SIDEKIQ_SUPPORTED=true
  - rvm: 2.1.10
    env: SAMPLE_APP=rails_4_2_8 SIDEKIQ_SUPPORTED=true
  - rvm: 2.1.10
    env: SAMPLE_APP=rails_5_0_3 SIDEKIQ_SUPPORTED=true TEST_AR=true
  - rvm: 2.1.10
    env: SAMPLE_APP=rails_5_1_1 SIDEKIQ_SUPPORTED=true TEST_AR=true
  include:
  - rvm: 2.1.10
    env: SIDEKIQ_VERSION=3.5.3 SAMPLE_APP=rails_4_1_16 SIDEKIQ_SUPPORTED=true
  - rvm: 2.1.10
    env: SIDEKIQ_VERSION=4.0 SAMPLE_APP=rails_4_1_16 SIDEKIQ_SUPPORTED=true
  - rvm: 2.4.1
    env: SAMPLE_APP=rails_4_2_8 STRATEGY=active_job SIDEKIQ_SUPPORTED=true
  - rvm: 2.4.1
    env: SAMPLE_APP=rails_5_0_3 STRATEGY=active_job SIDEKIQ_SUPPORTED=true
  - rvm: 2.4.1
    env: SAMPLE_APP=rails_5_1_1 STRATEGY=active_job SIDEKIQ_SUPPORTED=true
  - rvm: 2.3.4
    env: SAMPLE_APP=rails_4_0_0 STATE_MACHINE_VERSION=1.1.2
  - rvm: 2.4.1
    env: SAMPLE_APP=rails_5_1_1 STATE_MACHINES_ACTIVERECORD_VERSION=">=0.5"
  - rvm: 2.4.1
    env: SAMPLE_APP=rails_5_0_3 STATE_MACHINES_ACTIVERECORD_VERSION=0.4
  - rvm: 2.4.1
    env: SAMPLE_APP=rails_4_2_8 STATE_MACHINES_ACTIVERECORD_VERSION=0.3 STATE_MACHINES_VERSION=0.4
notifications:
  slack:
    secure: 6IAlvKplFv94Vaf0LES197FFIgt5cs1fUFA9820mmeoTGLDQcN+4Hpv+2/NRRqrfb2k+V+uFKmsuY8azHBoKHLIzH6d1T0NS82j54Ti+tm0iFZaKLHVp8TxuIge0/e0Niamod5mMziLTg6KcM+zNBYcoxS3th1mQNWQ2mtD9JZ8=
services:
  - redis-server