before_script: bundle exec rake bundle
script: bundle exec rake test
language: ruby
services: mongodb
rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7
  - 2.1.10
  - 2.0.0-p648
  - 1.9.3
  - 1.9.2
  - jruby-19mode
  - rbx-19mode
env:
  - SAMPLE_APP=rails_4_0_0
  - SAMPLE_APP=rails_3_2_13
  - SAMPLE_APP=rails_3_2_14_mongo
matrix:
  exclude:
    - rvm: 1.9.2
      env: SAMPLE_APP=rails_4_0_0
    - rvm: 1.9.2
      env: SAMPLE_APP=rails_3_2_14_mongo
