before_script: bundle exec rake bundle
script: bundle exec rake test
language: ruby
services: mongodb
rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7
  - 2.1.10
  - jruby-19mode
  - rbx-19mode
env:
  - SAMPLE_APP=rails_4_0_0
